# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SASjs VS Code Extension Run Tests on Windows

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [lts/hydrogen]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Package
        run: npm run vscode:prepublish
        env:
          CI: true
